from pathlib import Path

SLOTS_PER_EPOCH = 32
GENESIS_TIMESTAMP = 1_606_824_023
SECONDS_PER_SLOT = 12
MAX_WITHDRAWALS_PER_PAYLOAD = 16
MAX_BLS_TO_EXECUTION_CHANGES = 16
ENDPOINT = ""
DATA_DIR = Path.cwd() / "data"
